enter key now adds player to the table
Salem-1/Transcendence pull request #55
Opened 2024-01-21 13:41 UTC by Mohammed-Ehsan02

2024-01-21 13:41 UTC, Mohammed-Ehsan02 commented
Enter key now adds players to the table

2024-01-22 10:28 UTC, MahdyZ7 requested changes

2024-01-22 10:28 UTC, MahdyZ7 commented on srcs/nginx/frontend/templates/homePageBody.js
this did nothing, enter button does not work

2024-01-22 11:16 UTC, MahdyZ7 approved these changes

2024-01-22 11:16 UTC, merged